### ISSUE TITLE
[feat] : 로그인 및 회원가입 구현

### ISSUE THREAD

**Issue by mmihye** [33th-SOPT-SOPKATHON-4/Server#3]
## ✨ About Issue ✨
로그인 및 회원가입 구현

<br>

## ✅ Todo 
- [x] 기존 유저 로그인
- [x] 새로운 유저 회원가입
- [x] 새로운 유저 닉네임 생성
